micronaut:
  application:
    name: mnGcpObjectStorage
  object-storage:
    gcp:
      default:
        bucket: zebra-object-storage
netty:
  default:
    allocator:
      max-order: 3

gcp:
  project-id: 'winged-spotted-zebra'
  credentials:
    location: ./src/main/resources/sa-testing-pk.json